### ISSUE TITLE
Is it possible to get the MDP from each game ?

### ISSUE THREAD

**Issue by wuwushrek** [openai/atari-py#37]
Hi all (and Sorry if 'Issues' is not the appropriate place for this question) 
For the purpose of some IRL, I need to have the transition matrix of these games. Using the RAM version, I have 128*256*18 maximum of possible states. However, since the game is always determined by the initial state (and the future actions), can't I just sample all the initial states (and obtain the MDP from this) ? If yes how do I sample all the initial states ? Or do you have an advice on a simple (and efficient because I doubt the first one is) way to achieve my goal ?
Thanks in advance for your response

**Comment by christopherhesse** [comment]
I'm not 100% confident that the RAM contains the entire state of the system, since that is what `clone_state()` is supposed to give you.

Also I think there is only a single initial state, assuming you turn off frameskip, the environment is fully deterministic.  For each sequence of actions, you could define a state which is just that sequence of actions and get an MDP from that (adding in reward information if you actually know it for a given sequence).

This won't de-duplicate identical states (like for pressing a button that doesn't do anything) and quickly explodes to an unreasonable number of states.  If you want a more tractable MDP, try the toy text environments here: https://gym.openai.com/envs/#toy_text some of which include the transition probabilities so you can easily define an MDP.

**Comment by christopherhesse** [comment]
It sounds like from this other issue: https://github.com/openai/atari-py/issues/40 that `Solaris` actually does have different initial states based on `random_seed`, but I think most games have a single initial state.
