### ISSUE TITLE
Problem in making atari game environment in window 7 (missing MSVCP140D.dll system error)

### ISSUE THREAD

**Issue by Ali-Ai** [openai/atari-py#65]
I tested on Win 10 it was Okay. However, on Win 7 the error pops up.

**Comment by christopherhesse** [comment]
Thanks for filing the issue!  This was moved from https://github.com/openai/gym/issues/1592

We don't officially support windows, but a PR that fixes this issue would be cool to see.  Likely the DLL should be included in the Python wheel somehow.

**Comment by t1393988511** [comment]
Hi @Ali-Ai and @christopherhesse , the same problem happens to me.

Requiring msvcp140d.dll indicates that the compiled ale_c.dll is the debug version instead of the release version, which is not appropriate to be distributed to pypi.

Note that installing msvc++ redistributable won't help, as it only provides msvcp140.dll, not msvcp140d.dll. The only solution I guess is installing the full vs2017 that contains the vc++ sdk.

As I am not familiar with cmake, I also have no idea how the CMakeLists.txt should be modified to compile the release version instead of the debug version. Maybe this [post](https://stackoverflow.com/questions/7724569/debug-vs-release-in-cmake) will help.

Hope someone could fix it.

**Comment by JesseFarebro** [comment]
Hi,

This should now be fixed when `atari-py` gets merged into the ALE. We now build using `--config Release` on deployment: https://github.com/mgbellemare/Arcade-Learning-Environment/pull/272/files#diff-2eeaed663bd0d25b7e608891384b7298R49
